services:
  - type: web
    name: cnc-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: PORT
        value: 3001

  - type: web
    name: cnc-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: client
